### PR TITLE
87/task/html boilerplate

### PR DESCRIPTION
**Pull request by mnichols08**

### CODE REVIEW

**Review by Stacy-Riley — APPROVED** [review]
I approve

**Review by WillCBurroughs — APPROVED** [review]
Looks good!

**Comment by egpennington** [comment]
boiler plate html looks good

**Review by egpennington — APPROVED** [review]
add more mega tags later - 
<meta name="description" content="chingu.io voyage 47">
  <meta name="keywords" content="HTML, CSS, JavaScript, chingu">
  <meta name="author" content="add our names here...">

**Comment by mnichols08** [comment]
> add more mega tags later - [egpennington](https://github.com/egpennington)

Now is the best time to address changes to code. What did you have in mind?

**Comment by egpennington** [comment]
add these; 
(meta name="description" content="Chingu voyage 47")
(meta name="keywords" content="HTML, CSS, JavaScript, chingu, calendar, to-do app, task tracker")
(meta name="author" content="Amanda Libbey, Jayanti Neu, Stacy Riley, Tasmine Wakil, Mikey Nichols, Will Burroughs, Emmett Pennington")

**Comment by mnichols08** [comment]
If anybody wants to modify, change, or add to this code now is the time to do so. The proper way to do it would be to:
- [ ] switch to this branch
```
git fetch origin
git switch 87/task/html-boilerplate
```
- [ ] create a new branch for your code
- [ ] change, modify, or add code
- [ ] create pull request to merge your new branch with `87/task/html-boilerplate`

**Pull request merged**
