### PR TITLE
adds my name to contributors file

### PR DESCRIPTION
**Pull request by mnichols08**
This is what we will be doing in our Introduction to Git meeting today around 2:00pm EST

### CODE REVIEW

**Comment by mnichols08** [comment]
I am working on a Wiki Page for us to follow along and do this using the git terminal from scratch, please bear with me while I do so.

What is important to take from this particular page is the direction that this repository is going. Pay attention to the wording here: `<username>` wants to merge `nn` commits into `<branch-destination>` from `<branch-origin>`

The repository on the **right** is being uploaded into the repository on the **left**

**Comment by mnichols08** [comment]
I accidentally deleted the 22/documentation/insights branch, which consequently closed the pull request but I have reopened it now.

Please take some time to review this pull request, and observe the flow.

It is a pull request to merge my code that adds a link to my GitHub profile inside of the CONTRIBUTORS.md file

I am requesting to merge my code into the branch that I created when I opened up an issue that involved this code, and named it `22/documentation/insights`.

This is the work flow.
Discussion happens > Issue is created > Branch is created to solve an issue > developer is assigned a task > developer opens branch designated to issue > developer creates a new branch following our naming convention > developer writes code to fix issue > developer pushes code to repository > developer creates pull request to merge code into the branch that was created for said issue > code is reviewed > code passes or this cycle repeats.

**Review by Stacy-Riley — APPROVED** [review]
Looks good!

**Comment by mnichols08** [comment]
Resolved conflict and added a `-` hyphen before stacy-riley to create list item

**Review by egpennington — APPROVED** [review]
reviewed comment

**Pull request merged**
