### PR TITLE
Sprint I & II Progress

### PR DESCRIPTION
**Pull request by mnichols08**

### CODE REVIEW

**Comment by egpennington** [comment]
progress!

**Review by egpennington — DISMISSED** [review]
Progress

**Review by Stacy-Riley — DISMISSED** [review]
I approve

**Review by jayanti-neu — APPROVED** [review]

**Comment by mnichols08** [comment]
I've lowered the number of required approvals down two from each tier
- alpha no longer requires an approval to merge.
- beta requires 1 approval
- development requires 2 approvals
- production requires 3 approvals

**Review by egpennington — APPROVED** [review]
good

**Review by Stacy-Riley — APPROVED** [review]
I approve

**Pull request merged**
